package mcp

import mcpgo "github.com/mark3labs/mcp-go/mcp"

// ToolDefinitions returns the complete Unity tool manifest.
// Tool names must match the [McpTool] attributes in Unity C# code.
func ToolDefinitions() []mcpgo.Tool {
	return []mcpgo.Tool{
		// Scene tools
		mcpgo.NewTool("unity.scene.list",
			mcpgo.WithDescription("List all scenes in the build settings and currently open scenes"),
			mcpgo.WithBoolean("includeOpenState", mcpgo.Description("Include scene open/dirty state")),
		),
		mcpgo.NewTool("unity.scene.get_active",
			mcpgo.WithDescription("Get the currently active scene"),
		),
		mcpgo.NewTool("unity.scene.set_active",
			mcpgo.WithDescription("Set a loaded scene as the active scene"),
			mcpgo.WithString("path", mcpgo.Description("Scene asset path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.scene.open",
			mcpgo.WithDescription("Open a scene in the editor"),
			mcpgo.WithString("path", mcpgo.Description("Scene asset path"), mcpgo.Required()),
			mcpgo.WithBoolean("additive", mcpgo.Description("Open additively")),
		),
		mcpgo.NewTool("unity.scene.save",
			mcpgo.WithDescription("Save the current scene or a specific scene"),
			mcpgo.WithString("path", mcpgo.Description("Optional scene asset path")),
		),
		mcpgo.NewTool("unity.scene.create",
			mcpgo.WithDescription("Create a new empty scene"),
			mcpgo.WithBoolean("setupGameObjects", mcpgo.Description("Create default camera and light")),
		),
		mcpgo.NewTool("unity.scene.get_hierarchy",
			mcpgo.WithDescription("Get the full hierarchy of the current scene"),
			mcpgo.WithNumber("maxDepth", mcpgo.Description("Maximum hierarchy depth")),
		),
		mcpgo.NewTool("unity.scene.find_objects",
			mcpgo.WithDescription("Find objects in the scene by name or type"),
			mcpgo.WithString("name", mcpgo.Description("Object name filter")),
			mcpgo.WithString("type", mcpgo.Description("Component type name")),
			mcpgo.WithBoolean("includeInactive", mcpgo.Description("Include inactive objects")),
		),

		// GameObject tools
		mcpgo.NewTool("unity.gameobject.create",
			mcpgo.WithDescription("Create a new GameObject in the scene"),
			mcpgo.WithString("name", mcpgo.Description("Object name"), mcpgo.Required()),
			mcpgo.WithString("parentPath", mcpgo.Description("Parent hierarchy path")),
		),
		mcpgo.NewTool("unity.gameobject.delete",
			mcpgo.WithDescription("Delete a GameObject from the scene"),
			mcpgo.WithString("path", mcpgo.Description("Hierarchy path"), mcpgo.Required()),
			mcpgo.WithBoolean("confirm", mcpgo.Description("Confirm deletion"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.gameobject.rename",
			mcpgo.WithDescription("Rename a GameObject"),
			mcpgo.WithString("path", mcpgo.Description("Hierarchy path"), mcpgo.Required()),
			mcpgo.WithString("newName", mcpgo.Description("New name"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.gameobject.find",
			mcpgo.WithDescription("Find GameObjects by name, tag, or path"),
			mcpgo.WithString("name", mcpgo.Description("Object name to search for")),
			mcpgo.WithString("tag", mcpgo.Description("Tag to filter by")),
			mcpgo.WithString("path", mcpgo.Description("Hierarchy path to find by")),
			mcpgo.WithBoolean("includeInactive", mcpgo.Description("Include inactive objects")),
		),
		mcpgo.NewTool("unity.gameobject.get_components",
			mcpgo.WithDescription("Get all components on a GameObject"),
			mcpgo.WithString("path", mcpgo.Description("Hierarchy path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.gameobject.add_component",
			mcpgo.WithDescription("Add a component to a GameObject"),
			mcpgo.WithString("path", mcpgo.Description("Hierarchy path"), mcpgo.Required()),
			mcpgo.WithString("componentType", mcpgo.Description("Unity component type name"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.gameobject.remove_component",
			mcpgo.WithDescription("Remove a component from a GameObject"),
			mcpgo.WithString("path", mcpgo.Description("Hierarchy path"), mcpgo.Required()),
			mcpgo.WithString("componentType", mcpgo.Description("Unity component type name"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.gameobject.set_transform",
			mcpgo.WithDescription("Set transform position, rotation, or scale"),
			mcpgo.WithString("path", mcpgo.Description("Hierarchy path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.gameobject.set_active",
			mcpgo.WithDescription("Set a GameObject's active state"),
			mcpgo.WithString("path", mcpgo.Description("Hierarchy path"), mcpgo.Required()),
			mcpgo.WithBoolean("active", mcpgo.Description("Active state"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.gameobject.set_parent",
			mcpgo.WithDescription("Set a GameObject's parent"),
			mcpgo.WithString("path", mcpgo.Description("Hierarchy path"), mcpgo.Required()),
			mcpgo.WithString("parentPath", mcpgo.Description("New parent path")),
		),
		mcpgo.NewTool("unity.gameobject.duplicate",
			mcpgo.WithDescription("Duplicate a GameObject"),
			mcpgo.WithString("path", mcpgo.Description("Hierarchy path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.gameobject.get_hierarchy",
			mcpgo.WithDescription("Get children of a GameObject"),
			mcpgo.WithString("path", mcpgo.Description("Hierarchy path"), mcpgo.Required()),
		),

		// Asset tools
		mcpgo.NewTool("unity.asset.find",
			mcpgo.WithDescription("Find assets by name, type, or filter"),
			mcpgo.WithString("query", mcpgo.Description("Search query")),
			mcpgo.WithString("type", mcpgo.Description("Asset type filter")),
			mcpgo.WithNumber("limit", mcpgo.Description("Max results")),
			mcpgo.WithNumber("cursor", mcpgo.Description("Pagination cursor")),
		),
		mcpgo.NewTool("unity.asset.get_info",
			mcpgo.WithDescription("Get asset metadata"),
			mcpgo.WithString("path", mcpgo.Description("Asset path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.asset.import",
			mcpgo.WithDescription("Import an external file into the project"),
			mcpgo.WithString("sourcePath", mcpgo.Description("External file path"), mcpgo.Required()),
			mcpgo.WithString("destinationPath", mcpgo.Description("Asset destination path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.asset.delete",
			mcpgo.WithDescription("Delete an asset"),
			mcpgo.WithString("path", mcpgo.Description("Asset path"), mcpgo.Required()),
			mcpgo.WithBoolean("confirm", mcpgo.Description("Confirm deletion"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.asset.move",
			mcpgo.WithDescription("Move an asset"),
			mcpgo.WithString("sourcePath", mcpgo.Description("Source path"), mcpgo.Required()),
			mcpgo.WithString("destinationPath", mcpgo.Description("Destination path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.asset.copy",
			mcpgo.WithDescription("Copy an asset"),
			mcpgo.WithString("sourcePath", mcpgo.Description("Source path"), mcpgo.Required()),
			mcpgo.WithString("destinationPath", mcpgo.Description("Destination path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.asset.create_folder",
			mcpgo.WithDescription("Create a folder in the AssetDatabase"),
			mcpgo.WithString("path", mcpgo.Description("Folder path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.asset.refresh",
			mcpgo.WithDescription("Refresh the AssetDatabase"),
		),
		mcpgo.NewTool("unity.asset.get_dependencies",
			mcpgo.WithDescription("Get asset dependencies"),
			mcpgo.WithString("path", mcpgo.Description("Asset path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.asset.get_guid",
			mcpgo.WithDescription("Get the GUID for an asset path"),
			mcpgo.WithString("path", mcpgo.Description("Asset path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.asset.get_path",
			mcpgo.WithDescription("Get the asset path for a GUID"),
			mcpgo.WithString("guid", mcpgo.Description("Asset GUID"), mcpgo.Required()),
		),

		// Material tools
		mcpgo.NewTool("unity.material.create",
			mcpgo.WithDescription("Create a new material"),
			mcpgo.WithString("name", mcpgo.Description("Material name"), mcpgo.Required()),
			mcpgo.WithString("shaderName", mcpgo.Description("Shader name")),
			mcpgo.WithString("path", mcpgo.Description("Asset path")),
		),
		mcpgo.NewTool("unity.material.set_color",
			mcpgo.WithDescription("Set a color property on a material"),
			mcpgo.WithString("materialPath", mcpgo.Description("Material asset path"), mcpgo.Required()),
			mcpgo.WithString("propertyName", mcpgo.Description("Property name"), mcpgo.Required()),
			mcpgo.WithString("color", mcpgo.Description("Color as hex or name"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.material.set_float",
			mcpgo.WithDescription("Set a float property on a material"),
			mcpgo.WithString("materialPath", mcpgo.Description("Material asset path"), mcpgo.Required()),
			mcpgo.WithString("propertyName", mcpgo.Description("Property name"), mcpgo.Required()),
			mcpgo.WithNumber("value", mcpgo.Description("Float value"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.material.set_texture",
			mcpgo.WithDescription("Set a texture property on a material"),
			mcpgo.WithString("materialPath", mcpgo.Description("Material asset path"), mcpgo.Required()),
			mcpgo.WithString("propertyName", mcpgo.Description("Property name"), mcpgo.Required()),
			mcpgo.WithString("texturePath", mcpgo.Description("Texture asset path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.material.set_vector",
			mcpgo.WithDescription("Set a vector property on a material"),
			mcpgo.WithString("materialPath", mcpgo.Description("Material asset path"), mcpgo.Required()),
			mcpgo.WithString("propertyName", mcpgo.Description("Property name"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.material.set_int",
			mcpgo.WithDescription("Set an integer property on a material"),
			mcpgo.WithString("materialPath", mcpgo.Description("Material asset path"), mcpgo.Required()),
			mcpgo.WithString("propertyName", mcpgo.Description("Property name"), mcpgo.Required()),
			mcpgo.WithNumber("value", mcpgo.Description("Integer value"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.material.get_properties",
			mcpgo.WithDescription("Get all properties of a material"),
			mcpgo.WithString("materialPath", mcpgo.Description("Material asset path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.material.get_color",
			mcpgo.WithDescription("Get a color property from a material"),
			mcpgo.WithString("materialPath", mcpgo.Description("Material asset path"), mcpgo.Required()),
			mcpgo.WithString("propertyName", mcpgo.Description("Property name"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.material.get_float",
			mcpgo.WithDescription("Get a float property from a material"),
			mcpgo.WithString("materialPath", mcpgo.Description("Material asset path"), mcpgo.Required()),
			mcpgo.WithString("propertyName", mcpgo.Description("Property name"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.material.copy",
			mcpgo.WithDescription("Copy material settings from one material to another"),
			mcpgo.WithString("sourcePath", mcpgo.Description("Source material path"), mcpgo.Required()),
			mcpgo.WithString("destinationPath", mcpgo.Description("Destination material path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.shader.find",
			mcpgo.WithDescription("Find a shader by name"),
			mcpgo.WithString("name", mcpgo.Description("Shader name"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.shader.get_properties",
			mcpgo.WithDescription("Get properties of a shader"),
			mcpgo.WithString("shaderName", mcpgo.Description("Shader name"), mcpgo.Required()),
		),

		// Prefab tools
		mcpgo.NewTool("unity.prefab.create",
			mcpgo.WithDescription("Create a prefab from a GameObject in the scene"),
			mcpgo.WithNumber("gameObjectId", mcpgo.Description("GameObject instance ID"), mcpgo.Required()),
			mcpgo.WithString("path", mcpgo.Description("Prefab asset path")),
		),
		mcpgo.NewTool("unity.prefab.instantiate",
			mcpgo.WithDescription("Instantiate a prefab into the scene"),
			mcpgo.WithString("prefabPath", mcpgo.Description("Prefab asset path"), mcpgo.Required()),
			mcpgo.WithString("parentPath", mcpgo.Description("Parent hierarchy path")),
		),
		mcpgo.NewTool("unity.prefab.save",
			mcpgo.WithDescription("Save prefab changes"),
			mcpgo.WithString("prefabPath", mcpgo.Description("Prefab asset path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.prefab.open",
			mcpgo.WithDescription("Open prefab for editing"),
			mcpgo.WithString("prefabPath", mcpgo.Description("Prefab asset path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.prefab.close",
			mcpgo.WithDescription("Close prefab editing"),
		),
		mcpgo.NewTool("unity.prefab.get_info",
			mcpgo.WithDescription("Get prefab metadata"),
			mcpgo.WithString("prefabPath", mcpgo.Description("Prefab asset path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.prefab.apply_overrides",
			mcpgo.WithDescription("Apply prefab instance overrides"),
			mcpgo.WithString("prefabPath", mcpgo.Description("Prefab asset path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.prefab.revert_overrides",
			mcpgo.WithDescription("Revert prefab instance to original"),
			mcpgo.WithString("prefabPath", mcpgo.Description("Prefab asset path"), mcpgo.Required()),
		),

		// Script tools
		mcpgo.NewTool("unity.script.create",
			mcpgo.WithDescription("Create a new C# script"),
			mcpgo.WithString("name", mcpgo.Description("Script name"), mcpgo.Required()),
			mcpgo.WithString("content", mcpgo.Description("Script content")),
			mcpgo.WithString("path", mcpgo.Description("Script asset path")),
		),
		mcpgo.NewTool("unity.script.update",
			mcpgo.WithDescription("Update a script's content"),
			mcpgo.WithString("path", mcpgo.Description("Script asset path"), mcpgo.Required()),
			mcpgo.WithString("content", mcpgo.Description("New script content"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.script.delete",
			mcpgo.WithDescription("Delete a script"),
			mcpgo.WithString("path", mcpgo.Description("Script asset path"), mcpgo.Required()),
			mcpgo.WithBoolean("confirm", mcpgo.Description("Confirm deletion"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.script.get_content",
			mcpgo.WithDescription("Read a script's content"),
			mcpgo.WithString("path", mcpgo.Description("Script asset path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.script.compile_status",
			mcpgo.WithDescription("Check if scripts are compiling"),
		),
		mcpgo.NewTool("unity.script.wait_for_compilation",
			mcpgo.WithDescription("Wait for script compilation to complete"),
			mcpgo.WithNumber("timeoutSeconds", mcpgo.Description("Timeout in seconds")),
		),
		mcpgo.NewTool("unity.script.get_errors",
			mcpgo.WithDescription("Get compilation errors"),
		),
		mcpgo.NewTool("unity.script.execute_code",
			mcpgo.WithDescription("Execute C# code (requires Roslyn)"),
			mcpgo.WithString("code", mcpgo.Description("C# code to execute"), mcpgo.Required()),
		),

		// Console tools
		mcpgo.NewTool("unity.console.get_logs",
			mcpgo.WithDescription("Get Unity console logs"),
			mcpgo.WithNumber("limit", mcpgo.Description("Maximum number of entries")),
			mcpgo.WithString("filter", mcpgo.Description("Filter by log type")),
		),
		mcpgo.NewTool("unity.console.clear",
			mcpgo.WithDescription("Clear the Unity console"),
		),
		mcpgo.NewTool("unity.console.get_count",
			mcpgo.WithDescription("Get log counts by type"),
		),
		mcpgo.NewTool("unity.console.subscribe",
			mcpgo.WithDescription("Subscribe to new log entries"),
		),

		// Editor tools
		mcpgo.NewTool("unity.editor.get_state",
			mcpgo.WithDescription("Get the current editor state"),
		),
		mcpgo.NewTool("unity.editor.play",
			mcpgo.WithDescription("Enter play mode"),
		),
		mcpgo.NewTool("unity.editor.stop",
			mcpgo.WithDescription("Exit play mode"),
		),
		mcpgo.NewTool("unity.editor.pause",
			mcpgo.WithDescription("Toggle pause in play mode"),
		),
		mcpgo.NewTool("unity.editor.get_selection",
			mcpgo.WithDescription("Get the current editor selection"),
		),
		mcpgo.NewTool("unity.editor.set_selection",
			mcpgo.WithDescription("Set the editor selection"),
			mcpgo.WithString("instanceIds", mcpgo.Description("Comma-separated instance IDs"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.editor.ping_object",
			mcpgo.WithDescription("Ping an object in the Project window"),
			mcpgo.WithNumber("instanceId", mcpgo.Description("Instance ID"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.editor.execute_menu_item",
			mcpgo.WithDescription("Execute a menu command"),
			mcpgo.WithString("menuPath", mcpgo.Description("Menu item path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.editor.undo",
			mcpgo.WithDescription("Undo last operation"),
		),
		mcpgo.NewTool("unity.editor.redo",
			mcpgo.WithDescription("Redo last operation"),
		),

		// Profiler tools
		mcpgo.NewTool("unity.profiler.start",
			mcpgo.WithDescription("Start profiling"),
		),
		mcpgo.NewTool("unity.profiler.stop",
			mcpgo.WithDescription("Stop profiling"),
		),
		mcpgo.NewTool("unity.profiler.get_status",
			mcpgo.WithDescription("Get profiler status"),
		),
		mcpgo.NewTool("unity.profiler.get_memory_stats",
			mcpgo.WithDescription("Get memory statistics"),
		),
		mcpgo.NewTool("unity.profiler.get_rendering_stats",
			mcpgo.WithDescription("Get rendering statistics"),
		),
		mcpgo.NewTool("unity.profiler.get_script_stats",
			mcpgo.WithDescription("Get script execution statistics"),
		),
		mcpgo.NewTool("unity.profiler.get_samples",
			mcpgo.WithDescription("Get profiler samples"),
		),
		mcpgo.NewTool("unity.profiler.enable_module",
			mcpgo.WithDescription("Enable a profiler module"),
			mcpgo.WithString("moduleName", mcpgo.Description("Module name"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.profiler.disable_module",
			mcpgo.WithDescription("Disable a profiler module"),
			mcpgo.WithString("moduleName", mcpgo.Description("Module name"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.profiler.save_data",
			mcpgo.WithDescription("Save profiler data to file"),
			mcpgo.WithString("path", mcpgo.Description("File path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.profiler.load_data",
			mcpgo.WithDescription("Load profiler data from file"),
			mcpgo.WithString("path", mcpgo.Description("File path"), mcpgo.Required()),
		),
		mcpgo.NewTool("unity.profiler.clear_data",
			mcpgo.WithDescription("Clear profiler data"),
		),
	}
}
